### ISSUE TITLE
Always SADNESS / NEUTRAL emotion detect

### ISSUE THREAD

**Issue by sanketshahdev** [alshell7/VokaturiAndroid#1]
Always detecting SADNESS / NEUTRAL emotion.

**Comment by achandrashekhar** [comment]
I am facing this issue too

**Comment by alshell7** [comment]
Hey no worries, I will have a check on it, but I'm kind off busy with the other projects right now, so might get late until I come on this 😅 ..
Meanwhile cheers 😉 , the Vokaturi developers now, have extended official support for platforms targeting on ARM processors too (Android).
I prefer you should go with the library that is provided by them (yeah you're right, this repository might be deprecated soon),
Well here's the link where you can download it [Vokaturi SDK](https://developers.vokaturi.com/downloads/sdk)
Installation is pretty simple, go to `lib/open/android` folder of the extracted zip file (that holds the SDK), you'd find an *.aar file, using which you can integrate it with your Android project seamlessly 🌟
